name: halaqoh
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  cloud_firestore: ^4.4.4
  cupertino_icons: ^1.0.2
  external_app_launcher: ^3.1.0
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.1
  firebase_storage: ^11.0.15
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  get: 4.6.5
  google_sign_in: ^6.0.2
  iconly: ^1.0.1
  percent_indicator: ^4.2.3
  pinput: ^2.2.31
  step_progress_indicator: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - asset/image/
